<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
    <WasmMainJSPath>AppBundle\main.js</WasmMainJSPath>
    <OutputType>Exe</OutputType>
    <MSBuildEnableWorkloadResolver>true</MSBuildEnableWorkloadResolver>
  </PropertyGroup>

  <ItemGroup>
    <TrimmerRootDescriptor Include="Roots.xml" />
  </ItemGroup>

  <ItemGroup>
    <WasmExtraFilesToDeploy Include="AppBundle\app.css" />
    <WasmExtraFilesToDeploy Include="AppBundle\favicon.ico" />
    <WasmExtraFilesToDeploy Include="AppBundle\felt.svg" />
    <WasmExtraFilesToDeploy Include="AppBundle\index.html" />
    <WasmExtraFilesToDeploy Include="AppBundle\Logo.svg" />
    <WasmExtraFilesToDeploy Include="AppBundle\main.js" />
    <WasmExtraFilesToDeploy Include="AppBundle\staticwebapp.config.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="$(SkiaSharpVersion)" />
    <PackageReference Include="SkiaSharp.NativeAssets.WebAssembly" Version="$(SkiaSharpVersion)" />
    <PackageReference Include="HarfBuzzSharp" Version="8.3.1.3" />
    <PackageReference Include="HarfBuzzSharp.NativeAssets.WebAssembly" Version="8.3.1.3" />
    <PackageReference Include="Avalonia.Browser" Version="$(AvaloniaVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Solitaire\Solitaire.csproj" />
    <ProjectReference Include="../Solitaire.Platform.Browser/Solitaire.Platform.Browser.csproj" />
  </ItemGroup>

  <Import Project="WasmMemory.props" />

</Project>
