name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
    - release/*

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.100

      - name: Install wasm-tools
        run: dotnet workload install wasm-tools

      - name: Install DotNetCompress
        run: dotnet tool install --global DotNetCompress --version 1.0.0-preview.7 --no-cache

      - name: Publish .NET Project
        run: dotnet publish Solitaire.Browser/Solitaire.Browser.csproj -c Release -o release --nologo

      - name: Brotli Compress Output (dll)
        run: DotNetCompress -d Solitaire.Browser/bin/Release/net8.0-browser/browser-wasm/AppBundle/ -p '*.dll' -p '*.js' -p '*.symbols' -p '*.blat' -p '*.bin' -p '*.wasm'

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APP_DEPLOY_KEY }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "Solitaire.Browser/bin/Release/net8.0-browser/browser-wasm/AppBundle/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Modify this to where your SSG places the built HTML - could be `dist`, `build`... check your config          
          skip_app_build: true
          ###### End of Repository/Build Configurations ######
