name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - release/*

jobs:
  build_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - enableThreads: false
            folderName: "st"
          - enableThreads: true
            folderName: "mt"
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.101

      - name: Install wasm-tools
        run: dotnet workload install wasm-tools

      - name: Publish .NET Project
        run: dotnet publish Solitaire.Browser/Solitaire.Browser.csproj -c Release -p:WasmEnableThreads=${{matrix.enableThreads}} -o artifacts/${{matrix.folderName}}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.folderName }}
          path: artifacts/${{ matrix.folderName }}

  deploy_job:
    needs: [ build_job ]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Arrange folders
        run: |
          mkdir -p deploy/
          mkdir -p deploy/mt
          mv artifacts/st/* deploy/
          mv artifacts/mt/* deploy/mt/

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APP_DEPLOY_KEY }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "deploy"
          api_location: ""
          output_location: ""
          skip_app_build: true
